// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message-alliance.proto

package com.s4game.protocol;

public final class AllianceMessage {
  private AllianceMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CgAllianceListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CgAllianceList)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code CgAllianceList}
   *
   * <pre>
   * &#64;Id(1100)
   * </pre>
   */
  public static final class CgAllianceList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CgAllianceList)
      CgAllianceListOrBuilder {
    // Use CgAllianceList.newBuilder() to construct.
    private CgAllianceList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CgAllianceList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CgAllianceList defaultInstance;
    public static CgAllianceList getDefaultInstance() {
      return defaultInstance;
    }

    public CgAllianceList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CgAllianceList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.s4game.protocol.AllianceMessage.internal_static_CgAllianceList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.s4game.protocol.AllianceMessage.internal_static_CgAllianceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.s4game.protocol.AllianceMessage.CgAllianceList.class, com.s4game.protocol.AllianceMessage.CgAllianceList.Builder.class);
    }

    public static com.google.protobuf.Parser<CgAllianceList> PARSER =
        new com.google.protobuf.AbstractParser<CgAllianceList>() {
      public CgAllianceList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CgAllianceList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CgAllianceList> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s4game.protocol.AllianceMessage.CgAllianceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.s4game.protocol.AllianceMessage.CgAllianceList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CgAllianceList}
     *
     * <pre>
     * &#64;Id(1100)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CgAllianceList)
        com.s4game.protocol.AllianceMessage.CgAllianceListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s4game.protocol.AllianceMessage.internal_static_CgAllianceList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s4game.protocol.AllianceMessage.internal_static_CgAllianceList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s4game.protocol.AllianceMessage.CgAllianceList.class, com.s4game.protocol.AllianceMessage.CgAllianceList.Builder.class);
      }

      // Construct using com.s4game.protocol.AllianceMessage.CgAllianceList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.s4game.protocol.AllianceMessage.internal_static_CgAllianceList_descriptor;
      }

      public com.s4game.protocol.AllianceMessage.CgAllianceList getDefaultInstanceForType() {
        return com.s4game.protocol.AllianceMessage.CgAllianceList.getDefaultInstance();
      }

      public com.s4game.protocol.AllianceMessage.CgAllianceList build() {
        com.s4game.protocol.AllianceMessage.CgAllianceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.s4game.protocol.AllianceMessage.CgAllianceList buildPartial() {
        com.s4game.protocol.AllianceMessage.CgAllianceList result = new com.s4game.protocol.AllianceMessage.CgAllianceList(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.s4game.protocol.AllianceMessage.CgAllianceList) {
          return mergeFrom((com.s4game.protocol.AllianceMessage.CgAllianceList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.s4game.protocol.AllianceMessage.CgAllianceList other) {
        if (other == com.s4game.protocol.AllianceMessage.CgAllianceList.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.s4game.protocol.AllianceMessage.CgAllianceList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.s4game.protocol.AllianceMessage.CgAllianceList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CgAllianceList)
    }

    static {
      defaultInstance = new CgAllianceList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CgAllianceList)
  }

  public interface GcAllianceListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GcAllianceList)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code GcAllianceList}
   *
   * <pre>
   * &#64;Id(1101)
   * </pre>
   */
  public static final class GcAllianceList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GcAllianceList)
      GcAllianceListOrBuilder {
    // Use GcAllianceList.newBuilder() to construct.
    private GcAllianceList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GcAllianceList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GcAllianceList defaultInstance;
    public static GcAllianceList getDefaultInstance() {
      return defaultInstance;
    }

    public GcAllianceList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GcAllianceList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.s4game.protocol.AllianceMessage.internal_static_GcAllianceList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.s4game.protocol.AllianceMessage.internal_static_GcAllianceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.s4game.protocol.AllianceMessage.GcAllianceList.class, com.s4game.protocol.AllianceMessage.GcAllianceList.Builder.class);
    }

    public static com.google.protobuf.Parser<GcAllianceList> PARSER =
        new com.google.protobuf.AbstractParser<GcAllianceList>() {
      public GcAllianceList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GcAllianceList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GcAllianceList> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.s4game.protocol.AllianceMessage.GcAllianceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.s4game.protocol.AllianceMessage.GcAllianceList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GcAllianceList}
     *
     * <pre>
     * &#64;Id(1101)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GcAllianceList)
        com.s4game.protocol.AllianceMessage.GcAllianceListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.s4game.protocol.AllianceMessage.internal_static_GcAllianceList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.s4game.protocol.AllianceMessage.internal_static_GcAllianceList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.s4game.protocol.AllianceMessage.GcAllianceList.class, com.s4game.protocol.AllianceMessage.GcAllianceList.Builder.class);
      }

      // Construct using com.s4game.protocol.AllianceMessage.GcAllianceList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.s4game.protocol.AllianceMessage.internal_static_GcAllianceList_descriptor;
      }

      public com.s4game.protocol.AllianceMessage.GcAllianceList getDefaultInstanceForType() {
        return com.s4game.protocol.AllianceMessage.GcAllianceList.getDefaultInstance();
      }

      public com.s4game.protocol.AllianceMessage.GcAllianceList build() {
        com.s4game.protocol.AllianceMessage.GcAllianceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.s4game.protocol.AllianceMessage.GcAllianceList buildPartial() {
        com.s4game.protocol.AllianceMessage.GcAllianceList result = new com.s4game.protocol.AllianceMessage.GcAllianceList(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.s4game.protocol.AllianceMessage.GcAllianceList) {
          return mergeFrom((com.s4game.protocol.AllianceMessage.GcAllianceList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.s4game.protocol.AllianceMessage.GcAllianceList other) {
        if (other == com.s4game.protocol.AllianceMessage.GcAllianceList.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.s4game.protocol.AllianceMessage.GcAllianceList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.s4game.protocol.AllianceMessage.GcAllianceList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GcAllianceList)
    }

    static {
      defaultInstance = new GcAllianceList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GcAllianceList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CgAllianceList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CgAllianceList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GcAllianceList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GcAllianceList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034proto/message-alliance.proto\"\020\n\016CgAlli" +
      "anceList\"\020\n\016GcAllianceListB&\n\023com.s4game" +
      ".protocolB\017AllianceMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CgAllianceList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CgAllianceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CgAllianceList_descriptor,
        new java.lang.String[] { });
    internal_static_GcAllianceList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GcAllianceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GcAllianceList_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
